# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0e17cdb1-fb53-4f4b-b64a-8c76b58bd9f4'
  imageRepository: 'compose-img'
  containerRegistry: 'dockerazure.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  containerPath: '/app/test/TestResults'
  imgName: '$(containerRegistry)/$(imageRepository):$(tag)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'dockerazure'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: 'dockerazure'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'TCMTest(7489b9b9-8abe-4b02-a0d9-f09f368df55f)'
        azureContainerRegistry: '{"loginServer":"dockerazure.azurecr.io", "id" : "/subscriptions/7489b9b9-8abe-4b02-a0d9-f09f368df55f/resourceGroups/tcmdaily/providers/Microsoft.ContainerRegistry/registries/dockerazure"}'
        dockerComposeFile: '**/docker-compose.tests.yml'
        action: 'Build services'
        additionalImageTags: '$(Build.BuildId)'
        includeLatestTag: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'TCMTest(7489b9b9-8abe-4b02-a0d9-f09f368df55f)'
        azureContainerRegistry: '{"loginServer":"dockerazure.azurecr.io", "id" : "/subscriptions/7489b9b9-8abe-4b02-a0d9-f09f368df55f/resourceGroups/tcmdaily/providers/Microsoft.ContainerRegistry/registries/dockerazure"}'
        dockerComposeFile: '**/docker-compose.tests.yml'
        qualifyImageNames: false
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up --abort-on-container-exit'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(System.DefaultWorkingDirectory)'
    


   
