version: '3'

services:
  UnitTestProject1:
    environment: 
      - BLOWUP
    image: dockerazure.azurecr.io/compose-img:349
    build:
      context: .
    entrypoint: dotnet test --logger trx --results-directory /var/temp
    volumes:
      - $(System.DefaultWorkingDirectory):/var/temp
