version: '3'

services:
  UnitTestProject1:
    image: dockerazure.azurecr.io/compose-img:349
    build:
      context: .
    entrypoint: dotnet test --logger trx --results-directory /var/temp
    volumes:
      - ${a}:/var/temp
